export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';

export const REQUEST_SAVE_ROOM_SUCCESS = 'REQUEST_SAVE_ROOM_SUCCESS';
export const REQUEST_GET_ROOM_SUCCESS = "REQUEST_GET_ROOM_SUCCESS";

export const REQUEST_SAVE_DURATION_TYPE_SUCCESS = 'REQUEST_SAVE_DURATION_TYPE_SUCCESS';
export const REQUEST_GET_DURATION_TYPE_SUCCESS = 'REQUEST_GET_DURATION_TYPE_SUCCESS';

export const REQUEST_SAVE_PAYTYPE_SUCCESS = 'REQUEST_SAVE_PAYTYPE_SUCCESS';
export const REQUEST_GET_PAYTYPE_SUCCESS = "REQUEST_GET_PAYTYPE_SUCCESS";

export const REQUEST_GET_REGION_SUCCESS = 'REQUEST_GET_REGION_SUCCESS';
export const REQUEST_SAVE_REGION_SUCCESS = 'REQUEST_SAVE_REGION_SUCCESS';
export const REQUEST_SEARCH_REGION_SUCCESS = 'REQUEST_SEARCH_REGION_SUCCESS';

export const REQUEST_GET_COURSES_SUCCESS = 'REQUEST_GET_COURSES_SUCCESS';
export const REQUEST_GET_COURSE_SUCCESS = 'REQUEST_GET_COURSE_SUCCESS';
export const REQUEST_SAVE_COURSE_SUCCESS = 'REQUEST_SAVE_COURSE_SUCCESS';
export const REQUEST_SEARCH_COURSE_SUCCESS = 'REQUEST_SEARCH_COURSE_SUCCESS';


export const REQUEST_GET_PROFESSION_SUCCESS = 'REQUEST_GET_PROFESSION_SUCCESS';
export const REQUEST_SAVE_PROFESSION_SUCCESS = 'REQUEST_SAVE_PROFESSION_SUCCESS';

export const REQUEST_GET_TEST_CATEGORY_SUCCESS = 'REQUEST_GET_TEST_CATEGORY_SUCCESS';
export const REQUEST_SAVE_TEST_CATEGORY_SUCCESS = 'REQUEST_SAVE_TEST_CATEGORY_SUCCESS';

export const REQUEST_GET_REKLAMA_SUCCESS = 'REQUEST_GET_REKLAMA_SUCCESS';
export const REQUEST_SAVE_REKLAMA_SUCCESS = 'REQUEST_SAVE_REKLAMA_SUCCESS';

export const REQUEST_GET_TEACHER_SUCCESS = 'REQUEST_GET_TEACHER_SUCCESS';
export const REQUEST_SAVE_TEACHER_SUCCESS = 'REQUEST_SAVE_TEACHER_SUCCESS';

export const REQUEST_GET_STUDENT_SUCCESS = 'REQUEST_GET_STUDENT_SUCCESS';
export const REQUEST_GET_STUDENTS_SUCCESS = 'REQUEST_GET_STUDENTS_SUCCESS';
export const REQUEST_SAVE_STUDENT_SUCCESS = 'REQUEST_SAVE_STUDENT_SUCCESS';

export const REQUEST_SAVE_COURSE_CATEGORY_SUCCESS = 'REQUEST_SAVE_COURSE_CATEGORY_SUCCESS';
export const REQUEST_GET_COURSE_CATEGORIES_SUCCESS = 'REQUEST_GET_COURSE_CATEGORIES_SUCCESS';
export const REQUEST_GET_COURSE_CATEGORY_SUCCESS = 'REQUEST_GET_COURSE_CATEGORY_SUCCESS';


export const REQUEST_SAVE_TRIAL_CONTACT_TYPE_SUCCESS = 'REQUEST_SAVE_TRIAL_CONTACT_TYPE_SUCCESS';
export const REQUEST_GET_TRIAL_CONTACT_TYPE_SUCCESS = 'REQUEST_GET_TRIAL_CONTACT_TYPE_SUCCESS';

export const REQUEST_ATTACHMENT_SUCCESS = 'REQUEST_ATTACHMENT_SUCCESS';






